## Dependencies

In [3]:
import pandas as pd

# Step 1: Extracting the data

In [58]:
# Display the CSV file
datafile_df = pd.read_csv("../Group_Project_1/Life_Expectancy_Data.csv")

datafile_df. head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263,62,0.01,71.279624,65,1154,...,6,8.16,65,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271,64,0.01,73.523582,62,492,...,58,8.18,62,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268,66,0.01,73.219243,64,430,...,62,8.13,64,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272,69,0.01,78.184215,67,2787,...,67,8.52,67,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275,71,0.01,7.097109,68,3013,...,68,7.87,68,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

In [7]:
# Print the total of uniques values for the "Country" column
unique_countries = datafile_df["Country"].unique()

for country in unique_countries:
    print(country)

Afghanistan
Albania
Algeria
Angola
Argentina
Armenia
Australia
Austria
Azerbaijan
Bangladesh
Belarus
Belgium
Belize
Benin
Bhutan
Bosnia and Herzegovina
Botswana
Brazil
Bulgaria
Burkina Faso
Burundi
Cabo Verde
Cambodia
Cameroon
Canada
Central African Republic
Chad
Chile
China
Colombia
Comoros
Costa Rica
Croatia
Cyprus
Djibouti
Dominican Republic
Ecuador
El Salvador
Equatorial Guinea
Eritrea
Estonia
Ethiopia
Fiji
France
Gabon
Georgia
Germany
Ghana
Greece
Guatemala
Guinea
Guinea-Bissau
Guyana
Haiti
Honduras
India
Indonesia
Iraq
Ireland
Israel
Italy
Jamaica
Jordan
Kazakhstan
Kenya
Kiribati
Latvia
Lebanon
Lesotho
Liberia
Lithuania
Luxembourg
Madagascar
Malawi
Malaysia
Maldives
Mali
Malta
Mauritania
Mauritius
Mexico
Mongolia
Montenegro
Morocco
Mozambique
Myanmar
Namibia
Nepal
Netherlands
Nicaragua
Niger
Nigeria
Pakistan
Panama
Papua New Guinea
Paraguay
Peru
Philippines
Poland
Portugal
Romania
Russian Federation
Rwanda
Samoa
Sao Tome and Principe
Senegal
Serbia
Seychelles
Sierra Leone
Solomon Islands
South Africa
Spain
Sri Lanka
Suriname
Swaziland
Sweden
Syrian Arab Republic
Tajikistan
Thailand
Timor-Leste
Togo
Tonga
Trinidad and Tobago
Tunisia
Turkey
Turkmenistan
Uganda
Ukraine
Uruguay
Uzbekistan
Vanuatu
Zambia
Zimbabwe

In [22]:
# Total number of countries
unique_countries_count = datafile_df["Country"].nunique()

unique_countries_count

133

# Step 2: Organising the data

In [ ]:
# Define the world's main regions to sort the data:

# North America 
# South America 
# Central America 
# Carribean
# Asia 
# Oceania 
# Europe 
# Africa 

# Source: https://sciencing.com/10-geographic-regions-world-8774247.html

In [62]:
# Define the mapping of the countries per region
region_mapping = {
    "Africa": ["Algeria", "Angola", "Benin", "Botswana", "Burkina Faso", "Burundi", "Cabo Verde", "Cameroon", "Central African Republic", "Chad", "Comoros", "Djibouti", "Equatorial Guinea", "Eritrea", "Ethiopia", "Gabon", "Ghana", "Guinea", "Guinea-Bissau", "Kenya", "Lesotho", "Liberia", "Madagascar", "Malawi", "Mali", "Mauritania", "Mauritius", "Morocco", "Mozambique", "Namibia", "Niger", "Nigeria", "Rwanda", "Sao Tome and Principe", "Senegal", "Seychelles", "Sierra Leone", "South Africa", "Swaziland", "Togo", "Tunisia", "Uganda", "Zambia", "Zimbabwe"],
    "Europe": ["Albania", "Armenia", "Austria", "Azerbaijan", "Belarus", "Belgium", "Bosnia and Herzegovina", "Bulgaria", "Croatia", "Cyprus", "Estonia", "France", "Georgia", "Germany", "Greece", "Hungary", "Iceland", "Ireland", "Italy", "Latvia", "Lithuania", "Luxembourg", "Malta", "Montenegro", "Netherlands", "Norway", "Poland", "Portugal", "Romania", "Russian Federation", "Serbia", "Slovakia", "Slovenia", "Spain", "Sweden", "Ukraine"],
    "Oceania": ["Australia", "Fiji", "Kiribati", "Marshall Islands", "Micronesia", "Nauru", "New Zealand", "Palau", "Papua New Guinea", "Samoa", "Solomon Islands", "Tonga", "Tuvalu", "Vanuatu"],
    "Asia": ["Afghanistan", "Armenia", "Azerbaijan", "Bangladesh", "Bhutan", "Cambodia", "China", "Georgia", "India", "Indonesia", "Iraq", "Israel", "Japan", "Jordan", "Kazakhstan", "Kyrgyzstan", "Laos", "Lebanon", "Malaysia", "Maldives", "Mongolia", "Myanmar", "Nepal", "North Korea", "Oman", "Pakistan", "Palestine", "Philippines", "Qatar", "Saudi Arabia", "Singapore", "South Korea", "Sri Lanka", "Syria", "Syrian Arab Republic", "Tajikistan", "Thailand", "Timor-Leste", "Turkey", "Turkmenistan", "United Arab Emirates", "Uzbekistan", "Vietnam", "Yemen"],
    "Caribbean": ["Belize", "Dominican Republic", "Grenada", "Haiti", "Jamaica", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Trinidad and Tobago"],
    "Central America": ["Costa Rica", "El Salvador", "Guatemala", "Honduras", "Mexico", "Nicaragua", "Panama"],
    "South America": ["Argentina", "Brazil", "Chile", "Colombia", "Ecuador", "Guyana", "Paraguay", "Peru", "Suriname", "Uruguay"],
    "North America": ["Canada", "United States"]
}

# Add a "Region" column to the DataFrame based on the region_mapping dictionary
datafile_df["Region"] = datafile_df["Country"].apply(lambda x: next((region for region, countries in region_mapping.items() if x in countries), "Unknown"))

# Display the DataFrame with the "Region" column
datafile_df.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling,Region
0,Afghanistan,2015,Developing,65.0,263,62,0.01,71.279624,65,1154,...,8.16,65,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1,Asia
1,Afghanistan,2014,Developing,59.9,271,64,0.01,73.523582,62,492,...,8.18,62,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0,Asia
2,Afghanistan,2013,Developing,59.9,268,66,0.01,73.219243,64,430,...,8.13,64,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9,Asia
3,Afghanistan,2012,Developing,59.5,272,69,0.01,78.184215,67,2787,...,8.52,67,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8,Asia
4,Afghanistan,2011,Developing,59.2,275,71,0.01,7.097109,68,3013,...,7.87,68,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5,Asia

In [69]:
# Save the new data into CSV    
datafile_df.to_csv('datafile_per_region.csv', index=False)

In [64]:
# Count of the number of countries per region
value_counts = datafile_df["Region"].value_counts()

print(value_counts)

Africa             473
Europe             403
Asia               356
South America      130
Oceania            119
Central America     99
Caribbean           57
North America       12
Name: Region, dtype: int64

In [65]:
# Filter the DataFrame to include only data from 2004 to 2014
filtered_df = datafile_df[(datafile_df["Year"] >= 2004) & (datafile_df["Year"] <= 2014)]

filtered_df

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling,Region
1,Afghanistan,2014,Developing,59.9,271,64,0.01,73.523582,62,492,...,8.18,62,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0,Asia
2,Afghanistan,2013,Developing,59.9,268,66,0.01,73.219243,64,430,...,8.13,64,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9,Asia
3,Afghanistan,2012,Developing,59.5,272,69,0.01,78.184215,67,2787,...,8.52,67,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8,Asia
4,Afghanistan,2011,Developing,59.2,275,71,0.01,7.097109,68,3013,...,7.87,68,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5,Asia
5,Afghanistan,2010,Developing,58.8,279,74,0.01,79.679367,66,1989,...,9.20,66,0.1,553.328940,2883167.0,18.4,18.4,0.448,9.2,Asia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1640,Zimbabwe,2008,Developing,48.2,632,30,3.56,20.843429,75,0,...,4.96,75,20.5,325.678573,13558469.0,7.8,7.8,0.421,9.7,Africa
1641,Zimbabwe,2007,Developing,46.6,67,29,3.88,29.814566,72,242,...,4.47,73,23.7,396.998217,1332999.0,8.2,8.2,0.414,9.6,Africa
1642,Zimbabwe,2006,Developing,45.4,7,28,4.57,34.262169,68,212,...,5.12,7,26.8,414.796232,13124267.0,8.6,8.6,0.408,9.5,Africa
1643,Zimbabwe,2005,Developing,44.6,717,28,4.14,8.717409,65,420,...,6.44,68,30.3,444.765750,129432.0,9.0,9.0,0.406,9.3,Africa
1644,Zimbabwe,2004,Developing,44.3,723,27,4.36,0.000000,68,31,...,7.13,65,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2,Africa

In [66]:
print(filtered_df.columns)

Index(['Country', 'Year', 'Status', 'Life expectancy ', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B',
       'Measles ', ' BMI ', 'under-five deaths ', 'Polio', 'Total expenditure',
       'Diphtheria ', ' HIV/AIDS', 'GDP', 'Population',
       ' thinness  1-19 years', ' thinness 5-9 years',
       'Income composition of resources', 'Schooling', 'Region'],
      dtype='object')

In [94]:
# Clean column titles
new_column_names = {'infant deaths': 'Infant Deaths',
                    'percentage expenditure': 'Percentage Expenditure',
                    'Measles ': 'Measles',                 
                    ' BMI ': 'BMI', 
                    'under-five deaths ': 'Under-Five Deaths', 
                    'Total expenditure': 'Total Expenditure',
                    ' HIV/AIDS': 'HIV/AIDS',
                    'Income composition of resources': 'Income Composition of Resources'}

# Remove leading and trailing whitespaces from column names
filtered_df.columns = filtered_df.columns.str.strip()

# Create a copy of the DataFrame before renaming the columns
filtered_df_copy = filtered_df.copy()

# Rename the columns in the copied DataFrame
filtered_df_copy.rename(columns=new_column_names, inplace=True)

# Print the modified DataFrame
filtered_df_copy.head()

,Country,Year,Status,Life expectancy,Adult Mortality,Infant Deaths,Alcohol,Percentage Expenditure,Hepatitis B,Measles,...,Under-Five Deaths,Polio,Total Expenditure,Diphtheria,HIV/AIDS,GDP,Population,Income Composition of Resources,Schooling,Region
1,Afghanistan,2014,Developing,59.9,271,64,0.01,73.523582,62,492,...,86,58,8.18,62,0.1,612.696514,327582.0,0.476,10.0,Asia
2,Afghanistan,2013,Developing,59.9,268,66,0.01,73.219243,64,430,...,89,62,8.13,64,0.1,631.744976,31731688.0,0.470,9.9,Asia
3,Afghanistan,2012,Developing,59.5,272,69,0.01,78.184215,67,2787,...,93,67,8.52,67,0.1,669.959000,3696958.0,0.463,9.8,Asia
4,Afghanistan,2011,Developing,59.2,275,71,0.01,7.097109,68,3013,...,97,68,7.87,68,0.1,63.537231,2978599.0,0.454,9.5,Asia
5,Afghanistan,2010,Developing,58.8,279,74,0.01,79.679367,66,1989,...,102,66,9.20,66,0.1,553.328940,2883167.0,0.448,9.2,Asia

In [96]:
# Verify that the columns are correct 
# and that the ' thinness  1-19 years' and ' thinness 5-9 years' columns have been dropped
print(filtered_df_copy.columns)

Index(['Country', 'Year', 'Status', 'Life expectancy', 'Adult Mortality',
       'Infant Deaths', 'Alcohol', 'Percentage Expenditure', 'Hepatitis B',
       'Measles', 'BMI', 'Under-Five Deaths', 'Polio', 'Total Expenditure',
       'Diphtheria', 'HIV/AIDS', 'GDP', 'Population',
       'Income Composition of Resources', 'Schooling', 'Region'],
      dtype='object')

# Step 3: Creation of two separate DataFrames for analysing the countries per region more effectively

In [100]:
# Creation of the DataFrame 1 including the 'Africa', 'Asia' and 'Europe' regions

grouped = filtered_df.groupby('Region')
region_dataframes = {region: group for region, group in grouped}

# List of regions to include
regions_to_include = ['Africa', 'Asia', 'Europe']

# Use pd.concat to concatenate DataFrames from the specified regions
dataframe1 = pd.concat([region_dataframes[region] for region in regions_to_include])

dataframe1.head()

,Country,Year,Status,Life expectancy,Adult Mortality,Infant Deaths,Alcohol,Percentage Expenditure,Hepatitis B,Measles,...,Under-Five Deaths,Polio,Total Expenditure,Diphtheria,HIV/AIDS,GDP,Population,Income Composition of Resources,Schooling,Region
32,Algeria,2014,Developing,75.4,11,21,0.01,54.237318,95,0,...,24,95,7.21,95,0.1,547.851700,39113313.0,0.741,14.4,Africa
33,Algeria,2013,Developing,75.3,112,21,0.53,544.450743,95,25,...,24,95,7.12,95,0.1,5471.866766,38338562.0,0.737,14.4,Africa
34,Algeria,2012,Developing,75.1,113,21,0.66,555.926083,95,18,...,24,95,6.14,95,0.1,5564.825660,37565847.0,0.732,14.4,Africa
35,Algeria,2011,Developing,74.9,116,21,0.56,509.002041,95,112,...,24,95,5.29,95,0.1,5432.252300,36819558.0,0.724,14.0,Africa
36,Algeria,2010,Developing,74.7,119,21,0.45,430.717586,95,103,...,24,95,5.12,95,0.1,4463.394675,36117637.0,0.714,13.6,Africa

In [102]:
# Save the new DataFrame 1 in a CSV format
dataframe1.to_csv('datafile1_per_region.csv', index=False)

In [104]:
# Creation of the DataFrame 2 including the 'North America', 'Central America', 'South America' and 'Caribbean' regions

# List of regions to include
regions_to_include = ['North America', 'Central America', 'South America', 'Caribbean']

# Use pd.concat to concatenate DataFrames from the specified regions
dataframe2 = pd.concat([region_dataframes[region] for region in regions_to_include])

dataframe2.head()

,Country,Year,Status,Life expectancy,Adult Mortality,Infant Deaths,Alcohol,Percentage Expenditure,Hepatitis B,Measles,...,Under-Five Deaths,Polio,Total Expenditure,Diphtheria,HIV/AIDS,GDP,Population,Income Composition of Resources,Schooling,Region
314,Canada,2014,Developing,82.0,65,2,8.1,102.190217,55,418,...,2,91,1.45,91,0.1,544.43376,35544564.0,0.912,15.9,North America
315,Canada,2013,Developing,81.8,67,2,8.2,9733.228019,55,83,...,2,91,1.67,91,0.1,52413.72116,35155451.0,0.909,15.9,North America
316,Canada,2012,Developing,81.6,68,2,8.3,9748.636237,7,10,...,2,99,1.78,95,0.1,52496.69487,3475545.0,0.907,15.9,North America
317,Canada,2011,Developing,81.5,68,2,8.2,971.928038,7,803,...,2,87,1.82,87,0.1,5282.21760,3434278.0,0.903,15.9,North America
318,Canada,2010,Developing,81.2,7,2,8.4,8649.674911,56,99,...,2,88,11.20,89,0.1,47447.47620,345274.0,0.898,15.9,North America

In [105]:
# Save the new DataFrame 2 in a CSV format
dataframe2.to_csv('datafile2_per_region.csv', index=False)

### For the purpose of this study we dropped the 'Oceania' region